import { readFile, writeFile } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
const parts = await Promise.all(Array.from({length:14}, (_, i) => readFile(new URL(`assets/js/admin-parts/part${String(i+1).padStart(2,'0')}.txt`, root), 'utf8')));
const source = '// Generated by node scripts/build-admin.mjs. Edit admin-parts, then regenerate.\n' + parts.join('\n');
const target = new URL('assets/js/admin-bundle.js', root);
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8') !== source) throw new Error('admin-bundle.js is out of date');
} else await writeFile(target, source);
